import "./globals.css";
import { Inter } from "next/font/google";

import type { Metadata } from "next";
import { ActiveLink } from "./activeLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header>
					<nav>
						<ul className="flex justify-center gap-5 bg-cyan-300 p-5">
							<li>
								<ActiveLink href="/">Home</ActiveLink>
							</li>

							<li>
								<ActiveLink href="/products">All</ActiveLink>
							</li>
						</ul>
					</nav>
				</header>

				{children}
			</body>
		</html>
	);
}
